experiment_name: CONFIG_TEST_NAME
run_id: CONFIG_TEST_RUN_ID
work_dir: /app/model
train_temporal_range: ['3500-01-01', '3600-01-01']
valid_temporal_range: ['3600-01-01', '3700-01-01']
test_temporal_range: ['3700-01-01', '3800-01-01']
seed: 10
model: CudaLSTM
hidden_size: 20
dropout: 0.2
lstm_layers: 2
lstm_batch_norm: false
model_head_layer: regression
model_head_activation: linear
model_head_kwargs: {}
find_unused_parameters: false
strategy: null
hython_trainer: rnntrainer
loss_fn:
  _target_: hython.losses.RMSELoss
metric_fn:
  _target_: hython.metrics.MSEMetric
metric_name: MSEMetric
optimizer: adam
lr_scheduler: null
lr_scheduler_hython:
  mode: min
  factor: 0.5
  patience: 10
seq_length: 20
learning_rate: 0.001
batch: 16
epochs: 2
time_ray: false
gradient_clip:
  max_norm: 1
target_weights: even
predict_steps: 0
train_downsampler:
  _target_: hython.sampler.downsampler.RandomDownsampler
  frac_time: null
  frac_space: 0.01
valid_downsampler:
  _target_: hython.sampler.downsampler.RandomDownsampler
  frac_time: null
  frac_space: 0.01
test_downsampler: null
dynamic_downsampler:
  frac_time: 0.1
data_lazy_load: false
dataset: WflowSBM_HPC
num_workers_dataloader: 24
num_workers_per_trial: 1
cpu_per_worker: 6
gpu_per_worker: 1
trials: 4
data_source:
  xarray_kwargs:
    engine: zarr
    storage_options:
      client_kwargs:
        endpoint_url: https://objectstore.eodc.eu:2222
  s3:
    static_inputs: NEW_PATH
    dynamic_inputs: NEW_PATH
    target_variables: NEW_PATH
static_categorical_inputs: [wflow_landuse, wflow_soil]
static_inputs: [thetaS, thetaR, KsatVer, c]
dynamic_inputs: [precip, pet, temp]
target_variables: [vwc]
mask_variables: [mask_missing]
scaling_variant: minmax
scaling_use_cached: true
tracking_uri: null
model_logger:
  CudaLSTM:
    logger: local
    model_component: model
    model_name: ${model}
    model_uri: ${work_dir}/${experiment_name}_${run_id}/${model}.pt
    log: true
    load: false
training_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:
  - _target_: itwinai.plugins.hython.data.RNNDatasetGetterAndPreprocessor
    hython_trainer: ${hython_trainer}
    dynamic_inputs: ${dynamic_inputs}
    static_inputs: ${static_inputs}
    target_variables: ${target_variables}
    mask_variables: ${mask_variables}
    train_temporal_range: ${train_temporal_range}
    valid_temporal_range: ${valid_temporal_range}
    dataset: ${dataset}
    data_lazy_load: ${data_lazy_load}
    data_source: ${data_source}
    scaling_variant: ${scaling_variant}
    scaling_use_cached: ${scaling_use_cached}
    experiment_name: ${experiment_name}
    run_id: ${run_id}
    work_dir: ${work_dir}
    train_downsampler: ${train_downsampler}
    valid_downsampler: ${valid_downsampler}
    seq_length: ${seq_length}
  - _target_: itwinai.plugins.hython.trainer.RNNDistributedTrainer
    model: ${model}
    config:
      experiment: ${experiment_name}/${run_id}
      experiment_name: ${experiment_name}
      run_id: ${run_id}
      work_dir: ${work_dir}
      batch_size: ${batch}
      learning_rate: ${learning_rate}
      num_workers_dataloader: ${num_workers_dataloader}
      pin_gpu_memory: true
      hython_trainer: ${hython_trainer}
      dynamic_downsampler: ${dynamic_downsampler}
      seq_length: ${seq_length}
      target_variables: ${target_variables}
      dynamic_inputs: ${dynamic_inputs}
      static_inputs: ${static_inputs}
      optimizer: ${optimizer}
      lr_scheduler: ${lr_scheduler}
      target_weights: ${target_weights}
      hidden_size: ${hidden_size}
      dropout: ${dropout}
      lstm_layers: ${lstm_layers}
      lstm_batch_norm: ${lstm_batch_norm}
      model_head_layer: ${model_head_layer}
      model_head_activation: ${model_head_activation}
      model_head_kwargs: ${model_head_kwargs}
      loss_fn: ${loss_fn}
      metric_fn: ${metric_fn}
      metric_name: ${metric_name}
      gradient_clip: ${gradient_clip}
      predict_steps: ${predict_steps}
      model_logger: ${model_logger}
    strategy: ${strategy}
    epochs: ${epochs}
    measure_gpu_data: true
    measure_communication_overhead: true
    measure_epoch_time: true
    run_id: $(run_id)
    random_seed: ${seed}
    profiling_wait_epochs: 1
    profiling_warmup_epochs: 1
    logger:
      _target_: itwinai.loggers.LoggersCollection
      loggers:
      - _target_: itwinai.loggers.ConsoleLogger
        log_freq: 1
      - _target_: itwinai.loggers.MLFlowLogger
        experiment_name: ${experiment_name}
        run_name: ${run_id}
        log_freq: batch
        tracking_uri: ${tracking_uri}
hpo:
  _target_: itwinai.pipeline.Pipeline
  steps:
  - _target_: itwinai.plugins.hython.data.RNNDatasetGetterAndPreprocessor
    hython_trainer: ${hython_trainer}
    dynamic_inputs: ${dynamic_inputs}
    static_inputs: ${static_inputs}
    target_variables: ${target_variables}
    mask_variables: ${mask_variables}
    train_temporal_range: ${train_temporal_range}
    valid_temporal_range: ${valid_temporal_range}
    dataset: ${dataset}
    data_lazy_load: ${data_lazy_load}
    data_source: ${data_source}
    scaling_variant: ${scaling_variant}
    scaling_use_cached: ${scaling_use_cached}
    experiment_name: ${experiment_name}
    run_id: ${run_id}
    work_dir: ${work_dir}
    train_downsampler: ${train_downsampler}
    valid_downsampler: ${valid_downsampler}
  - _target_: itwinai.plugins.hython.trainer.RNNDistributedTrainer
    model: ${model}
    config:
      experiment: ${experiment_name}/${run_id}
      experiment_name: ${experiment_name}
      run_id: ${run_id}
      work_dir: ${work_dir}
      batch_size: ${batch}
      learning_rate: ${learning_rate}
      num_workers_dataloader: ${num_workers_dataloader}
      pin_gpu_memory: true
      hython_trainer: ${hython_trainer}
      seq_length: ${seq_length}
      target_variables: ${target_variables}
      dynamic_inputs: ${dynamic_inputs}
      static_inputs: ${static_inputs}
      optimizer: ${optimizer}
      lr_scheduler: ${lr_scheduler}
      target_weights: ${target_weights}
      hidden_size: ${hidden_size}
      dropout: ${dropout}
      lstm_layers: ${lstm_layers}
      lstm_batch_norm: ${lstm_batch_norm}
      model_head_layer: ${model_head_layer}
      model_head_activation: ${model_head_activation}
      model_head_kwargs: ${model_head_kwargs}
      loss_fn: ${loss_fn}
      metric_fn: ${metric_fn}
      metric_name: ${metric_name}
      gradient_clip: ${gradient_clip}
      predict_steps: ${predict_steps}
      model_logger: ${model_logger}
    time_ray: ${time_ray}
    strategy: ${strategy}
    epochs: ${epochs}
    measure_gpu_data: true
    measure_communication_overhead: true
    measure_epoch_time: true
    run_id: $(run_id)
    random_seed: ${seed}
    profiling_wait_epochs: 1
    profiling_warmup_epochs: 1
    logger:
      _target_: itwinai.loggers.LoggersCollection
      loggers:
      - _target_: itwinai.loggers.ConsoleLogger
        log_freq: 1
      - _target_: itwinai.loggers.MLFlowLogger
        experiment_name: ${experiment_name}
        run_name: ${run_id}
        log_freq: batch
        tracking_uri: ${tracking_uri}
    ray_scaling_config:
      _target_: ray.train.ScalingConfig
      num_workers: ${num_workers_per_trial}
      use_gpu: true
      resources_per_worker:
        CPU: ${cpu_per_worker}
        GPU: ${gpu_per_worker}
    ray_tune_config:
      _target_: ray.tune.TuneConfig
      num_samples: ${trials}
      scheduler: null
    ray_run_config:
      _target_: ray.train.RunConfig
      storage_path: ${itwinai.cwd:}/ray_checkpoints
      name: EURAC-HPO-Experiment
    ray_search_space:
      batch_size:
        type: qrandint
        lower: 128
        upper: 1024
        q: 128
      optim_lr:
        type: uniform
        lower: 0.0001
        upper: 0.01
      hidden_size:
        type: randint
        lower: 16
        upper: 512
      dropout:
        type: choice
        categories: [0.1, 0.2, 0.3, 0.4, 0.5]
      seq_length:
        type: qrandint
        lower: 90
        upper: 365
        q: 30
      interval_value:
        type: choice
        categories: [3, 5, 10]
