FROM ubuntu:22.04 as build

RUN groupadd -r appuser && useradd -r -g appuser appuser

RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3.11 1

RUN curl -fsSL https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.1-linux-x86_64.tar.gz | tar -xz -C /opt/ && \
    ln -s /opt/julia-1.10.1/bin/julia /usr/local/bin/julia

WORKDIR /app

RUN mkdir /app/env /app/data/run_default /app/env/repo /output/run_default/outstate && \
    chmod -R 777 /app/data /output /app/env/repo

COPY Project.toml Manifest.toml /app/env/
RUN julia --project=/app/env -e 'using Pkg; Pkg.instantiate()'

COPY ./src/run_wflow.sh /usr/bin/run_wflow
COPY ./src/wflow.jl /usr/bin/wflow
COPY ./src/get_data.py /usr/bin/get_data.py

RUN chmod +x /usr/bin/run_wflow /usr/bin/wflow /usr/bin/get_data.py

FROM ubuntu:22.04

RUN groupadd -r appuser && useradd -r -g appuser appuser

COPY --from=build /usr/local/bin/julia /usr/local/bin/julia
COPY --from=build /usr/bin/python3.11 /usr/bin/python3.11
COPY --from=build /usr/bin/pip3.11 /usr/bin/pip3.11
COPY --from=build /app /app
COPY --from=build /usr/bin/run_wflow /usr/bin/run_wflow
COPY --from=build /usr/bin/wflow /usr/bin/wflow

ENV JULIA_DEPOT_PATH=/app/env/repo
ENV JULIA_PROJECT=/app/env

WORKDIR /app
USER appuser

