# Description: Parameters for the Hydromt CWL workflow
# This is passed as input to the CWL workflow
# --------------------------------------------

# Region of interest
# {'subbasin':[ 11.4750, 46.8717 ], 'strord':3}"
region: "{'subbasin': [11.4750, 46.8720]}" 
# Resolution of the Model
res: 0.00899999
# Precipitation forcing dataset
precip_fn: "cerra_land_stac"
# Wflow.ini configuration file
setupconfig:
  class: File
  path: "https://raw.githubusercontent.com/interTwin-eu/HyDroForM/refs/heads/openeo-integration/inputs/inputs_hydromt/wflow.ini"
# HydroMT Data Catalog
catalog: 
  class: File
  path: "https://raw.githubusercontent.com/interTwin-eu/HyDroForM/refs/heads/openeo-integration/inputs/inputs_hydromt/catalog.yaml""
# Script to update the Wflow.ini configuration file
config_gen:
  class: File
  path: "https://raw.githubusercontent.com/interTwin-eu/HyDroForM/refs/heads/openeo-integration/inputs/inputs_hydromt/config_gen.py"
# Data volume to mount while we use local data


# !cwltool --verbose --no-read-only --force-docker-pull --outdir ./hydromt-output hydromt-build-workflow.cwl#hydromt-workflow params.yaml


# cwltool --verbose --no-read-only --force-docker-pull --outdir ./hydromt-output hydromt-build-workflow.cwl#hydromt-workflow params.yaml > output.log 2>&1 